#!/bin/sh
set -e
current=$(git symbolic-ref --short HEAD)
echorun git checkout master
echorun git fetch
echorun git merge --ff-only
echorun git checkout $current
echorun git fetch
echorun git merge --no-edit --stat master

# Not going to use submodules:
# echorun git submodule update --init --recursive || return
# riastradh suggests git fetch; git merge --ff-only
